name: Build and deploy Producer

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: net7daprcontainer.azurecr.io
  AZURE_WEBAPP_NAME_CONTAINER: net7daprcontainer

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: Development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push it to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGISTRY_LOGIN_SERVER }}/net7dapr-producer:${{ github.sha }}
        file: ./DemoMicroservices/Producer/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: docker_build_push_acr

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n producer-container -g NextjsApp --server net7daprcontainer.azurecr.io --username  ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
            az containerapp update -n producer-container -g NextjsApp --image net7daprcontainer.azurecr.io/producer-container:${{ github.sha }}
